name: Deploy to Heroku (Server)

on:
  push:
    branches:
      - master
    paths:
      - "packages/server/**"
      - ".github/workflows/backend.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy yarn.lock file to packages/server 
        run: cp yarn.lock packages/server/
      - name: Commit yarn.lock file
        run: git add . & git commit -m "Add yarn.lock file"
      - name: Add server remote origin
        run: git remote add heroku-server https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_SERVER_APP_NAME }}.git
      - name: Deploy server to Heroku
        run: git push heroku-server `git subtree split --prefix packages/server master`:refs/heads/master --force
